"""Initial migration

Revision ID: 13dc6c3ce250
Revises: a66283095433
Create Date: 2024-05-20 13:34:34.118383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dc6c3ce250'
down_revision = 'a66283095433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_by', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('disliked_by', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('disliked_by')
        batch_op.drop_column('liked_by')

    # ### end Alembic commands ###
