"""Initial migration

Revision ID: 22cf0581e61d
Revises: 
Create Date: 2024-05-19 01:31:18.634096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cf0581e61d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=False),
    sa.Column('runtime', sa.String(length=20), nullable=False),
    sa.Column('plot', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=1000), nullable=True),
    sa.Column('img_path', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
