"""Initial migration

Revision ID: 24124da83288
Revises: 714f41be777b
Create Date: 2024-05-19 18:35:29.422481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24124da83288'
down_revision = '714f41be777b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
