"""Initial migration

Revision ID: cece22035464
Revises: 13dc6c3ce250
Create Date: 2024-05-20 13:43:33.268081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cece22035464'
down_revision = '13dc6c3ce250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_state', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dislike_state', sa.Boolean(), nullable=True))
        batch_op.drop_column('liked_by')
        batch_op.drop_column('disliked_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disliked_by', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('liked_by', sa.BLOB(), nullable=True))
        batch_op.drop_column('dislike_state')
        batch_op.drop_column('like_state')

    # ### end Alembic commands ###
