"""Initial migration

Revision ID: d8495aff7ac9
Revises: 
Create Date: 2024-05-20 11:10:41.949166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8495aff7ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=False),
    sa.Column('runtime', sa.String(length=20), nullable=False),
    sa.Column('plot', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('profile_pic', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=1000), nullable=True),
    sa.Column('img_path', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['movie_name'], ['movies.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
