"""Initial migration

Revision ID: e1646a7ec205
Revises: cece22035464
Create Date: 2024-05-20 13:48:57.035262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1646a7ec205'
down_revision = 'cece22035464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('like_state')
        batch_op.drop_column('dislike_state')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_chats', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('disliked_chats', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disliked_chats')
        batch_op.drop_column('liked_chats')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislike_state', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('like_state', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
